# Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN'.
application_df = application_df.drop(columns=['EIN'])
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [4]:
# Look at NAME value counts for binning
application_name_counts = application_df['NAME'].value_counts()
application_name_counts

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [5]:
# Choose a cutoff value and create a list of names_replace to be replaced
# use the variable name names_to_replace

cutoff_value = 5
names_to_replace = application_name_counts[application_name_counts < cutoff_value].index.tolist()

# Replace names in the dataframe with 'Other'
for name in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(name, 'Other')

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                19803
PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
                                                                     ...
GUILDS OF THE SANTA FE OPERA INC                                         5
FAMILY MOTOR COACH ASSOCIATION                                           5
JAMESTOWN SOCIETY                                                        5
MOST WORSHIPFUL PRINCE HALL GRAND LODGE OF FREE & ACCEPTED MASONS        5
PTA HAWAII CONGRESS                                                      5
Name: NAME, Length: 403, dtype: int64

In [6]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 500
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts
classification_counts

<bound method IndexOpsMixin.value_counts of 0        C1000
1        C2000
2        C3000
3        C2000
4        C1000
         ...
34294    C1000
34295    C3000
34296    C2000
34297    C3000
34298    C1000
Name: CLASSIFICATION, Length: 34299, dtype: object>

In [9]:
# Look at CLASSIFICATION value counts where the count is greater than 1
classification_counts = application_df["CLASSIFICATION"].value_counts()
classification_counts_gt1 = classification_counts[classification_counts > 1]

classification_counts_gt1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 1000
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_ACTS MINISTRY,NAME_ACTS MISSIONS,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [12]:
# Split our preprocessed data into our features and target arrays

X = application_df.drop(columns="IS_SUCCESSFUL")

y = application_df["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Compile, Train and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.


# Create a sequential model
nn = tf.keras.models.Sequential()

# Input layer
nn.add(tf.keras.layers.Dense(units=128, activation='relu', input_dim=X_train_scaled.shape[1]))


# First hidden layer
nn.add(tf.keras.layers.Dense(units=64, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=32, activation='relu'))


# Third hidden layer
nn.add(tf.keras.layers.Dense(units=16, activation='relu'))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 128)               57216

 dense_1 (Dense)             (None, 64)                8256

 dense_2 (Dense)             (None, 32)                2080

 dense_3 (Dense)             (None, 16)                528

 dense_4 (Dense)             (None, 1)                 17

=================================================================
Total params: 68097 (266.00 KB)
Trainable params: 68097 (266.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [16]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
729/729 [==============================] - 4s 4ms/step - loss: 0.4691 - accuracy: 0.7801 - val_loss: 0.4451 - val_accuracy: 0.7879
Epoch 2/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4289 - accuracy: 0.7972 - val_loss: 0.4397 - val_accuracy: 0.7937
Epoch 3/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4239 - accuracy: 0.7992 - val_loss: 0.4445 - val_accuracy: 0.7913
Epoch 4/100
729/729 [==============================] - 3s 4ms/step - loss: 0.4213 - accuracy: 0.8000 - val_loss: 0.4422 - val_accuracy: 0.7906
Epoch 5/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4196 - accuracy: 0.8015 - val_loss: 0.4425 - val_accuracy: 0.7906
Epoch 6/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4189 - accuracy: 0.8007 - val_loss: 0.4460 - val_accuracy: 0.7908
Epoch 7/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4180 - accuracy: 0.8013 - val_loss: 0.4474 - val_accuracy: 0.7925
Epoch 8/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4172 - accuracy: 0.8011 - val_loss: 0.4454 - val_accuracy: 0.7881
Epoch 9/100
729/729 [==============================] - 3s 3ms/step - loss: 0.4162 - accuracy: 0.8030 - val_loss: 0.4488 - val_accuracy: 0.7913
Epoch 10/100
729/729 [==============================] - 3s 4ms/step - loss: 0.4152 - accuracy: 0.8032 - val_loss: 0.4487 - val_accuracy: 0.7915
Epoch 11/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4144 - accuracy: 0.8033 - val_loss: 0.4576 - val_accuracy: 0.7894
Epoch 12/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4141 - accuracy: 0.8026 - val_loss: 0.4497 - val_accuracy: 0.7879
Epoch 13/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4133 - accuracy: 0.8038 - val_loss: 0.4499 - val_accuracy: 0.7877
Epoch 14/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4132 - accuracy: 0.8031 - val_loss: 0.4512 - val_accuracy: 0.7879
Epoch 15/100
729/729 [==============================] - 3s 4ms/step - loss: 0.4124 - accuracy: 0.8053 - val_loss: 0.4510 - val_accuracy: 0.7879
Epoch 16/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4121 - accuracy: 0.8039 - val_loss: 0.4535 - val_accuracy: 0.7872
Epoch 17/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4107 - accuracy: 0.8038 - val_loss: 0.4543 - val_accuracy: 0.7874
Epoch 18/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4108 - accuracy: 0.8048 - val_loss: 0.4568 - val_accuracy: 0.7894
Epoch 19/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4106 - accuracy: 0.8046 - val_loss: 0.4552 - val_accuracy: 0.7869
Epoch 20/100
729/729 [==============================] - 4s 5ms/step - loss: 0.4098 - accuracy: 0.8061 - val_loss: 0.4581 - val_accuracy: 0.7889
Epoch 21/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4085 - accuracy: 0.8057 - val_loss: 0.4515 - val_accuracy: 0.7867
Epoch 22/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4084 - accuracy: 0.8069 - val_loss: 0.4595 - val_accuracy: 0.7879
Epoch 23/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4074 - accuracy: 0.8060 - val_loss: 0.4601 - val_accuracy: 0.7862
Epoch 24/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4072 - accuracy: 0.8067 - val_loss: 0.4545 - val_accuracy: 0.7886
Epoch 25/100
729/729 [==============================] - 3s 3ms/step - loss: 0.4068 - accuracy: 0.8064 - val_loss: 0.4618 - val_accuracy: 0.7881
Epoch 26/100
729/729 [==============================] - 3s 4ms/step - loss: 0.4062 - accuracy: 0.8075 - val_loss: 0.4573 - val_accuracy: 0.7877
Epoch 27/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4059 - accuracy: 0.8072 - val_loss: 0.4619 - val_accuracy: 0.7872
Epoch 28/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4055 - accuracy: 0.8081 - val_loss: 0.4605 - val_accuracy: 0.7864
Epoch 29/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4053 - accuracy: 0.8070 - val_loss: 0.4562 - val_accuracy: 0.7847
Epoch 30/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4046 - accuracy: 0.8083 - val_loss: 0.4671 - val_accuracy: 0.7860
Epoch 31/100
729/729 [==============================] - 3s 4ms/step - loss: 0.4042 - accuracy: 0.8074 - val_loss: 0.4625 - val_accuracy: 0.7867
Epoch 32/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4031 - accuracy: 0.8085 - val_loss: 0.4648 - val_accuracy: 0.7869
Epoch 33/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4030 - accuracy: 0.8087 - val_loss: 0.4658 - val_accuracy: 0.7857
Epoch 34/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4032 - accuracy: 0.8087 - val_loss: 0.4620 - val_accuracy: 0.7864
Epoch 35/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4024 - accuracy: 0.8082 - val_loss: 0.4611 - val_accuracy: 0.7886
Epoch 36/100
729/729 [==============================] - 3s 4ms/step - loss: 0.4031 - accuracy: 0.8088 - val_loss: 0.4653 - val_accuracy: 0.7838
Epoch 37/100
729/729 [==============================] - 3s 3ms/step - loss: 0.4022 - accuracy: 0.8087 - val_loss: 0.4710 - val_accuracy: 0.7881
Epoch 38/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4020 - accuracy: 0.8092 - val_loss: 0.4628 - val_accuracy: 0.7872
Epoch 39/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4011 - accuracy: 0.8091 - val_loss: 0.4605 - val_accuracy: 0.7847
Epoch 40/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4008 - accuracy: 0.8096 - val_loss: 0.4659 - val_accuracy: 0.7852
Epoch 41/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4004 - accuracy: 0.8095 - val_loss: 0.4750 - val_accuracy: 0.7860
Epoch 42/100
729/729 [==============================] - 3s 4ms/step - loss: 0.4002 - accuracy: 0.8098 - val_loss: 0.4715 - val_accuracy: 0.7874
Epoch 43/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4001 - accuracy: 0.8086 - val_loss: 0.4800 - val_accuracy: 0.7855
Epoch 44/100
729/729 [==============================] - 2s 3ms/step - loss: 0.4000 - accuracy: 0.8092 - val_loss: 0.4779 - val_accuracy: 0.7852
Epoch 45/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3997 - accuracy: 0.8102 - val_loss: 0.4740 - val_accuracy: 0.7872
Epoch 46/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3990 - accuracy: 0.8096 - val_loss: 0.4783 - val_accuracy: 0.7855
Epoch 47/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3990 - accuracy: 0.8101 - val_loss: 0.4791 - val_accuracy: 0.7857
Epoch 48/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3982 - accuracy: 0.8095 - val_loss: 0.4845 - val_accuracy: 0.7850
Epoch 49/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3984 - accuracy: 0.8107 - val_loss: 0.4989 - val_accuracy: 0.7867
Epoch 50/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3982 - accuracy: 0.8104 - val_loss: 0.4999 - val_accuracy: 0.7886
Epoch 51/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3996 - accuracy: 0.8094 - val_loss: 0.4819 - val_accuracy: 0.7847
Epoch 52/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3986 - accuracy: 0.8105 - val_loss: 0.4960 - val_accuracy: 0.7850
Epoch 53/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3988 - accuracy: 0.8099 - val_loss: 0.4925 - val_accuracy: 0.7852
Epoch 54/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3983 - accuracy: 0.8097 - val_loss: 0.4855 - val_accuracy: 0.7850
Epoch 55/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3978 - accuracy: 0.8099 - val_loss: 0.4907 - val_accuracy: 0.7840
Epoch 56/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3978 - accuracy: 0.8110 - val_loss: 0.5069 - val_accuracy: 0.7850
Epoch 57/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3977 - accuracy: 0.8112 - val_loss: 0.5094 - val_accuracy: 0.7847
Epoch 58/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3965 - accuracy: 0.8113 - val_loss: 0.5148 - val_accuracy: 0.7850
Epoch 59/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3966 - accuracy: 0.8109 - val_loss: 0.5125 - val_accuracy: 0.7860
Epoch 60/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3965 - accuracy: 0.8114 - val_loss: 0.5029 - val_accuracy: 0.7857
Epoch 61/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3958 - accuracy: 0.8107 - val_loss: 0.4936 - val_accuracy: 0.7864
Epoch 62/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3978 - accuracy: 0.8108 - val_loss: 0.4837 - val_accuracy: 0.7860
Epoch 63/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3970 - accuracy: 0.8108 - val_loss: 0.4897 - val_accuracy: 0.7845
Epoch 64/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3958 - accuracy: 0.8110 - val_loss: 0.5000 - val_accuracy: 0.7857
Epoch 65/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3955 - accuracy: 0.8120 - val_loss: 0.5043 - val_accuracy: 0.7862
Epoch 66/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3955 - accuracy: 0.8115 - val_loss: 0.5338 - val_accuracy: 0.7816
Epoch 67/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3952 - accuracy: 0.8111 - val_loss: 0.5313 - val_accuracy: 0.7852
Epoch 68/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3950 - accuracy: 0.8120 - val_loss: 0.5140 - val_accuracy: 0.7845
Epoch 69/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3954 - accuracy: 0.8110 - val_loss: 0.5111 - val_accuracy: 0.7864
Epoch 70/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3963 - accuracy: 0.8113 - val_loss: 0.5266 - val_accuracy: 0.7850
Epoch 71/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3951 - accuracy: 0.8118 - val_loss: 0.5103 - val_accuracy: 0.7864
Epoch 72/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3951 - accuracy: 0.8109 - val_loss: 0.5091 - val_accuracy: 0.7864
Epoch 73/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3947 - accuracy: 0.8119 - val_loss: 0.5131 - val_accuracy: 0.7867
Epoch 74/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3940 - accuracy: 0.8115 - val_loss: 0.5081 - val_accuracy: 0.7862
Epoch 75/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3946 - accuracy: 0.8119 - val_loss: 0.5251 - val_accuracy: 0.7845
Epoch 76/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3952 - accuracy: 0.8114 - val_loss: 0.5078 - val_accuracy: 0.7889
Epoch 77/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3945 - accuracy: 0.8112 - val_loss: 0.5131 - val_accuracy: 0.7877
Epoch 78/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3948 - accuracy: 0.8113 - val_loss: 0.4991 - val_accuracy: 0.7864
Epoch 79/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3941 - accuracy: 0.8115 - val_loss: 0.5527 - val_accuracy: 0.7862
Epoch 80/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3939 - accuracy: 0.8124 - val_loss: 0.5637 - val_accuracy: 0.7850
Epoch 81/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3939 - accuracy: 0.8125 - val_loss: 0.5443 - val_accuracy: 0.7898
Epoch 82/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3932 - accuracy: 0.8124 - val_loss: 0.5281 - val_accuracy: 0.7860
Epoch 83/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3940 - accuracy: 0.8123 - val_loss: 0.5276 - val_accuracy: 0.7862
Epoch 84/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3929 - accuracy: 0.8123 - val_loss: 0.5555 - val_accuracy: 0.7852
Epoch 85/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3939 - accuracy: 0.8117 - val_loss: 0.5280 - val_accuracy: 0.7862
Epoch 86/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3932 - accuracy: 0.8123 - val_loss: 0.5433 - val_accuracy: 0.7855
Epoch 87/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3954 - accuracy: 0.8117 - val_loss: 0.5055 - val_accuracy: 0.7867
Epoch 88/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3928 - accuracy: 0.8115 - val_loss: 0.5356 - val_accuracy: 0.7869
Epoch 89/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3932 - accuracy: 0.8117 - val_loss: 0.5545 - val_accuracy: 0.7847
Epoch 90/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3936 - accuracy: 0.8113 - val_loss: 0.5249 - val_accuracy: 0.7862
Epoch 91/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3931 - accuracy: 0.8115 - val_loss: 0.5585 - val_accuracy: 0.7847
Epoch 92/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3944 - accuracy: 0.8108 - val_loss: 0.5301 - val_accuracy: 0.7872
Epoch 93/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3926 - accuracy: 0.8114 - val_loss: 0.5390 - val_accuracy: 0.7857
Epoch 94/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3921 - accuracy: 0.8116 - val_loss: 0.5586 - val_accuracy: 0.7855
Epoch 95/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3924 - accuracy: 0.8124 - val_loss: 0.5534 - val_accuracy: 0.7862
Epoch 96/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3922 - accuracy: 0.8119 - val_loss: 0.5357 - val_accuracy: 0.7855
Epoch 97/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3921 - accuracy: 0.8118 - val_loss: 0.5728 - val_accuracy: 0.7867
Epoch 98/100
729/729 [==============================] - 3s 4ms/step - loss: 0.3934 - accuracy: 0.8121 - val_loss: 0.5443 - val_accuracy: 0.7852
Epoch 99/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3920 - accuracy: 0.8114 - val_loss: 0.6116 - val_accuracy: 0.7857
Epoch 100/100
729/729 [==============================] - 2s 3ms/step - loss: 0.3934 - accuracy: 0.8116 - val_loss: 0.5503 - val_accuracy: 0.7867

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 0.5320 - accuracy: 0.7910 - 317ms/epoch - 1ms/step
Loss: 0.5319518446922302, Accuracy: 0.7909621000289917

In [19]:
# Save and export the results to an HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")

# Alphabet Soup Funding Analysis Report
**Overview of the Analysis:**
The primary objective of this analysis is to leverage the power of machine learning, particularly deep learning, to create a binary classification model that can predict the success of applicants funded by Alphabet Soup. This tool will assist Alphabet Soup in making informed decisions about which organizations to fund based on the likelihood of their success.

**Results:**

**Data Preprocessing:**

**Target Variable:**

**IS_SUCCESSFUL:** This indicates whether the funds provided by Alphabet Soup were used effectively by the organization.

**Features:**

All the columns present in the dataset, except for EIN and IS_SUCCESSFUL, were used as features. This includes APPLICATION_TYPE, AFFILIATION, CLASSIFICATION, USE_CASE, ORGANIZATION, STATUS, INCOME_AMT, SPECIAL_CONSIDERATIONS, ASK_AMT, and NAME.

**Variables Removed:**

**EIN:** This column was removed as it is an identification column and does not provide any significant information to determine the success of an organization.

**Compiling, Training, and Evaluating the Model:**

**Model Structure:**

Input Layer: 128 neurons with ReLU activation function.

First Hidden Layer: 64 neurons with ReLU activation function.

Second Hidden Layer: 32 neurons with ReLU activation function.

Third Hidden Layer: 16 neurons with ReLU activation function.

Output Layer: 1 neuron with Sigmoid activation function since it's a binary classification problem.

**Model Compilation:**

Optimizer: Adam

Loss function: Binary Crossentropy

Metrics: Accuracy

**Model Performance:**

The model's accuracy on the test set was found to be 79%.

**Steps to Optimize Model Performance:**

The data was preprocessed by binning values of categorical columns that had a large number of unique values. Specifically, values in NAME, APPLICATION_TYPE, and CLASSIFICATION columns were grouped into an 'Other' category if they occurred fewer times than a set cutoff value.
Data was then converted into a numerical format using one-hot encoding (pd.get_dummies).

The data was standardized using StandardScaler to have zero mean and unit variance.

The deep learning model was designed with multiple layers and neurons to capture the underlying patterns in the data. The model was trained over 100 epochs.

**Summary:**

The deep learning model designed for predicting the success of applicants funded by Alphabet Soup provides a mechanism for understanding the key factors that determine whether an organization will use the funds effectively. The model's accuracy indicates its effectiveness in making these predictions.

However, deep learning models can sometimes be seen as a 'black box', and it might be challenging to interpret which features had the most influence on the predictions.

**Recommendation:**

A different approach could be to use ensemble learning methods, such as Random Forest. This model can provide insights into feature importance, allowing Alphabet Soup to understand which factors are the most critical in determining an organization's success. This is also less prone to overfitting compared to deep neural networks and can sometimes achieve comparable or even better performance with the right hyperparameter tuning.